---
- hosts: controller
  gather_facts: false
  tasks:
    - name: Return Zuul log artifacts for data plane adoption jobs
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: make test-minimal output
                url: controller/data-plane-adoption-tests-repo/data-plane-adoption/tests/logs/
              - name: secrets.yaml passed to make test-minimal
                url: controller/data-plane-adoption-tests-repo/data_plane_adoption/secrets.yaml
              - name: vars.yaml passed to make test-minimal
                url: controller/data-plane-adoption-tests-repo/data_plane_adoption/vars.yaml
              - name: Podified control plane - pod logs
                url: controller/pod/
              - name: standalone deployment logs
                url: standalone/
              - name: ci-framework logs
                url: ci-framework-data/logs/
