- hosts: all
  name: validate-buildsys-tags playbook
  tasks:
    - name: Set zuul-log-path fact
      include_role:
        name: set-zuul-log-path-fact

    - name: Temporary install centos-packager from EPEL for CS9
      shell:
        cmd: |
          sudo {{ ansible_pkg_mgr }} install -y 'dnf-command(config-manager)';
          sudo {{ ansible_pkg_mgr }} config-manager --set-enabled crb;
          sudo {{ ansible_pkg_mgr }} install -y epel-release;
          sudo {{ ansible_pkg_mgr }} install -y centos-packager;
          sudo {{ ansible_pkg_mgr }} remove -y epel-release
      changed_when: true
      when: ansible_distribution_major_version|int == 9

    - name: Validate buildsys tag updates
      shell:
        cmd: |
          set -e -x
          # Install requirements
          YUM="{{ ansible_pkg_mgr }}"
          PROJECT="{{ zuul.project.name }}"
          sudo $YUM install -y wget yum-utils createrepo git yum
          python3 -m venv  --system-site-packages .venv
          . .venv/bin/activate
          pip install 'ruamel.yaml<=0.18.3' rdopkg
          pushd {{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}/buildsys-tags
          # define logs variable with the URL wher logs will be pushed
          export logs="https://logserver.rdoproject.org/{{ zuul_log_path }}/buildset"
          export WORKSPACE="{{ ansible_user_dir }}/workspace"
          mkdir -p $WORKSPACE
          case $PROJECT in
          rdoinfo)
            export INFO_DIR="{{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/rdoinfo'].src_dir | default('src/review.rdoproject.org/rdoinfo') }}"
            export INFO_FILE=rdo-full.yml
            export VALIDATE_SCRIPT=validate_updates.sh
            ;;
          nfvinfo)
            export INFO_DIR="{{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/nfvinfo'].src_dir | default('src/review.rdoproject.org/nfvinfo') }}"
            export INFO_FILE=nfv.yml
            export VALIDATE_SCRIPT=validate_updates_nfv.sh
            ;;
          esac
          bash ./create_temporary_repos.sh $INFO_DIR $WORKSPACE/logs $INFO_FILE
          ln -s $WORKSPACE/logs $WORKSPACE/buildset
          case $PROJECT in
          rdoinfo)
            bash ./${VALIDATE_SCRIPT} $WORKSPACE/logs $INFO_DIR
            ;;
          nfvinfo)
            bash ./${VALIDATE_SCRIPT} $WORKSPACE/logs
            ;;
          esac
          popd
      changed_when: true
